### ISSUE TITLE
Upload packages from CI

### ISSUE THREAD

**Issue by gromakovsky** [serokell/tezos-packaging#63] opened 2020-07-24 17:20 UTC
# Clarification and motivation

Currently in order to upload Ubuntu/Fedora packages some manual actions are required. It's inconvenient and we'd like to automate that process as much as possible.

# Acceptance criteria

1. CI is capable of uploading packages for Ubuntu and Fedora to repositories we are using.
2. I am not sure what's the best option to trigger this action. Either manually (if it's possible at all) or when something happens (e. g. a new tag is pushed or some special branch is updated). So it's part of the task to figure it out.

P. S. Note that some time ago we tried to do it for our old packaging in #46.

**Comment by ixahedron** [comment] 2021-09-01 15:23
AFAIU this is now a duplicate of #287, and that one has a better roadmap.

**Closed by ixahedron** 2021-09-01 15:23 UTC
